// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALodPIe9Kv-o4la3_94JrTDWtCnbiuEss',
    appId: '1:551660439778:web:923b87a2d38939971076bb',
    messagingSenderId: '551660439778',
    projectId: 'uppuveli-by-dsk',
    authDomain: 'uppuveli-by-dsk.firebaseapp.com',
    storageBucket: 'uppuveli-by-dsk.firebasestorage.app',
    measurementId: 'G-JS7YGHCQTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVCMw7alHILpurRmlRdWlUdHGkP3-03M0',
    appId: '1:551660439778:android:2c17b859035aa4751076bb',
    messagingSenderId: '551660439778',
    projectId: 'uppuveli-by-dsk',
    storageBucket: 'uppuveli-by-dsk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiVRcvYQIZ5LynJuAGjpOJ72BPHuKTEZ4',
    appId: '1:551660439778:ios:34c380f7a20afab21076bb',
    messagingSenderId: '551660439778',
    projectId: 'uppuveli-by-dsk',
    storageBucket: 'uppuveli-by-dsk.firebasestorage.app',
    iosBundleId: 'com.example.uppuveli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiVRcvYQIZ5LynJuAGjpOJ72BPHuKTEZ4',
    appId: '1:551660439778:ios:34c380f7a20afab21076bb',
    messagingSenderId: '551660439778',
    projectId: 'uppuveli-by-dsk',
    storageBucket: 'uppuveli-by-dsk.firebasestorage.app',
    iosBundleId: 'com.example.uppuveli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALodPIe9Kv-o4la3_94JrTDWtCnbiuEss',
    appId: '1:551660439778:web:fdd26e7414790ea81076bb',
    messagingSenderId: '551660439778',
    projectId: 'uppuveli-by-dsk',
    authDomain: 'uppuveli-by-dsk.firebaseapp.com',
    storageBucket: 'uppuveli-by-dsk.firebasestorage.app',
    measurementId: 'G-711FQ2R2HN',
  );
}
