// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_cS7tVotayOon2KA83oISGqrOk4MX-DY',
    appId: '1:98005017484:web:012e7a175706a2c4daaca9',
    messagingSenderId: '98005017484',
    projectId: 'uppuveli-hotel-app',
    authDomain: 'uppuveli-hotel-app.firebaseapp.com',
    storageBucket: 'uppuveli-hotel-app.firebasestorage.app',
    measurementId: 'G-HOTEL-APP-ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_cS7tVotayOon2KA83oISGqrOk4MX-DY',
    appId: '1:98005017484:android:012e7a175706a2c4daaca9',
    messagingSenderId: '98005017484',
    projectId: 'uppuveli-hotel-app',
    storageBucket: 'uppuveli-hotel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_cS7tVotayOon2KA83oISGqrOk4MX-DY',
    appId: '1:98005017484:ios:012e7a175706a2c4daaca9',
    messagingSenderId: '98005017484',
    projectId: 'uppuveli-hotel-app',
    storageBucket: 'uppuveli-hotel-app.firebasestorage.app',
    iosBundleId: 'com.example.uppuveli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_cS7tVotayOon2KA83oISGqrOk4MX-DY',
    appId: '1:98005017484:ios:012e7a175706a2c4daaca9',
    messagingSenderId: '98005017484',
    projectId: 'uppuveli-hotel-app',
    storageBucket: 'uppuveli-hotel-app.firebasestorage.app',
    iosBundleId: 'com.example.uppuveli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_cS7tVotayOon2KA83oISGqrOk4MX-DY',
    appId: '1:98005017484:web:012e7a175706a2c4daaca9',
    messagingSenderId: '98005017484',
    projectId: 'uppuveli-hotel-app',
    authDomain: 'uppuveli-hotel-app.firebaseapp.com',
    storageBucket: 'uppuveli-hotel-app.firebasestorage.app',
    measurementId: 'G-HOTEL-APP-ID',
  );
}
